name: Dokku materialscloud deploy

on:
  workflow_run:
    workflows:
      - Voila test
    types: [completed]
    branches: [master]

jobs:
  Dokku-prod-deploy:
    name: Dokku prod deploy
    runs-on: ubuntu-latest

    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    steps:
      - name: Cloning repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Push to dokku
        uses: dokku/github-action@master
        with:
          git_remote_url: 'ssh://dokku@materialscloud.io:22/osscar-quantum-mechanics'
          ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }}
        if: github.event_name != 'pull_request'

